### ISSUE TITLE
Connecting to Neo4J Desktop

### ISSUE THREAD

**Issue by youngbrett** [StefanTerdell/Speja#1]
Hi  --

I couldn't get a valid connection to Neo4J.  Which version of Neo4J Desktop did you use?  I fear that the changes to Bolt in the latest version broke the code.  The error I'm getting is "Reason: The remote server returned an error: (415) Unsupported Media Type." 

Thank you.

**Comment by StefanTerdell** [comment]
Hi @youngbrett ! Sorry, can't actually remember 😅 Been a long time since I did any work on this, as you can see from the commits. You're probably better off ripping out the guts of it and rebuilding it yourself with fresh APIs to be honest (and you're more than welcome to). Let me know if you manage to salvage anything useful 🙂
